name: projet_covoiturage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_ui_auth: ^1.0.0 
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.3
  http: ^1.2.2
  flutter_map:
  latlong2:
  location:
  intl: ^0.19.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^6.2.1
  firebase_messaging: ^15.1.5






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  logger: ^1.1.0

 

flutter:
  uses-material-design: true
  assets:
    - lib/assets/v1.jpg
    - lib/assets/v.jpg
    - lib/assets/ls.png
    - lib/assets/voiture.jpg
    - lib/assets/voituree.jpg
    - lib/assets/v2.jpg
    - lib/assets/v3.jpg
    - lib/assets/p.jpg








  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
